sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.1.188
    port: 3306
    database: sky_take_out
    username: root
    password: Aa2289496264#@
  redis:
    host: 192.168.1.188
    port: 6379
    password: Aa2289496264#@
    database: 0
  minio:
    endpoint: http://192.168.1.188:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: public
  wechat:
    appid: wx0610706d76bafee5
    secret: b229aa902d541c2bc28fc4d152291772
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php